language: python
dist: xenial
sudo: true
python:
- "3.6"
- "3.7"

branches:
  only:
  - master
  # Allow tagged releases in the format v1.0
  - /^v\d+\.\d+.*$/

cache: pip

install:
- "pip install -Ur ./travis/requirements.txt"

script:
- "pytest"

after_success:
- codecov

env:
- PYTHONPATH=.
